### ISSUE TITLE
Clicking the link after searching for a user produces an error

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#78]
I searched for the test accounts I created, after clicking on one of the accounts I was given an ajax error

![image](https://cloud.githubusercontent.com/assets/22599103/23677663/ababcc7c-0346-11e7-9e00-e040568db297.png)

**Comment by ShawnClake** [comment]
Oops. Forgot to change the component names for the AJAX handlers for the User component

Fixed in latest push.

**Comment by QuinnBast** [comment]
Now getting the following error:

![image](https://cloud.githubusercontent.com/assets/22599103/23678185/aae1e75c-0348-11e7-92e0-4e6bb392850c.png)

And after the commit I cannot view the default profile and am getting the following error:

![image](https://cloud.githubusercontent.com/assets/22599103/23678204/bf81e28e-0348-11e7-989c-9513387dd9cb.png)

no stack trace

**Comment by QuinnBast** [comment]
No longer get the big ERROR message when trying to view my own profile; still getting this error when clicking on a user after searching

![image](https://cloud.githubusercontent.com/assets/22599103/23678485/f9e57430-0349-11e7-9263-8dc2862acf46.png)

**Comment by QuinnBast** [comment]
My wonderful commit resolves issues with searching for users.
I'm tired.
